### ISSUE TITLE
Support full LSP specification

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/lsp#2]
Add support for all protocol specifications.

Ref: https://microsoft.github.io/language-server-protocol/specification

This shard can be used by other languages and tools like ameba, amber, lucky, etc

/cc @veelenga, @eliasjpr, @elorest, @drujensen, @paulcsmith

**Comment by paulcsmith** [comment]
@faustinoaq I'm not very familiar with this, is there something I should do in Lucky to enable this?

Thanks so much for all your work on making Crystal tooling awesome :D

![thumbs-up-300x199](https://user-images.githubusercontent.com/22394/39773953-7d7be964-52c7-11e8-9e0a-1e9cfac3b70f.jpg)

**Comment by faustinoaq** [comment]
@paulcsmith Yeah, thank you for your comment!, :+1: 

> is there something I should do in Lucky to enable this?

Not yet, I'm still working on this :sunglasses: 

CLI tools would implement this and use some flag like  `amber --server` or `lucky --server`

Then you configure that in your editor using an lsp-client to get specific code-completion, diagnostics, code actions and more.

> I'm not very familiar with this

the main use-case is to enable specific tools capabilities in almost every editor with an lsp client

See [Any developer Any Language Any Tool](https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol)

**Comment by paulcsmith** [comment]
Oh, that is insanely cool! Ping me when you need some help on my end and I'll give implementing it a shot 👍
